name: Knit R Markdown

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.Rmd'
      - '**/*.R'
      - '**/*.r'
      - '**/*.rds'
      - '**/*.csv' 
      - '**/*.yaml'

jobs:
  knit:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2
          
      - name: Install dependencies (respect pinned versions)
        run: |
          Rscript -e "options(repos = c(CRAN='https://cran.r-project.org', CRANextra='https://cran.r-project.org/src/contrib/Archive')); install.packages('remotes')"
          Rscript -e "install.packages('remotes', repos = 'https://cran.r-project.org')"
          # Fail early if DESCRIPTION is missing
          Rscript -e "if (!file.exists('DESCRIPTION')) stop('DESCRIPTION file is missing')"
          # Install exactly as pinned in DESCRIPTION
          Rscript -e "remotes::install_deps(dependencies = TRUE, upgrade = 'never')"
          # Verify installed versions match DESCRIPTION
          Rscript -e "remotes::dev_package_deps(dependencies = TRUE) -> deps; if (any(deps$diff != 'OK')) { print(deps); stop('Package version mismatch detected') }"

      - name: Knit Rmd to md
        run: rmarkdown::render("predict_risk.Rmd", output_format = "md_document")
        shell: Rscript {0}

      # commit knitted .md file back to repo
      - name: Commit and push knitted file
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add predict_risk.md
          git commit -m "update predict_risk.md"
          git push
