name: Knit R Markdown

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.Rmd'
      - '**/*.R'
      - '**/*.r'
      - '**/*.rds'
      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Knit Rmd to md
        run: rmarkdown::render("predict_risk.Rmd", output_format = "md_document")
        shell: Rscript {0}

      # commit knitted .md file back to repo
      - name: Commit and push knitted file
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add analysis.md
          git commit -m "update predict_risk.md"
          git push